name: TypeScript Compiler Validator

on: [push]

jobs:
  checktypes:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      - run: npm run tsc
      - run: npm run lint
