name: TypeScript Compiler Validator
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - run: echo "🔎 Сейчас будет произведен поиск ошибок в typeScript"
      - run: npm run ts
          with:
            node-version: ${{ matrix.node-version }}
